version: "3"
services:
  frontend:
    build: ./front
    expose:
      - 80
    depends_on:
      - strapi
    restart: always
    container_name: frontend_car_base
    environment:
      VIRTUAL_HOST: raportserwisowy.pl
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./api/app:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./api/data:/var/lib/postgresql/data

networks:
  default:
    external:
      name: nginx-proxy
