version: "3"
services:
  frontend:
    build: ./front
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: raportserwisowy.pl
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: raportserwisowy.pl
      LETSENCRYPT_EMAIL: andrzejmarek116@gmail.com
  strapi:
    image: strapi/strapi
    env_file: ./api/app/.env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      VIRTUAL_HOST: api.raportserwisowy.pl
      VIRTUAL_PORT: 1337
      LETSENCRYPT_HOST: api.raportserwisowy.pl
      LETSENCRYPT_EMAIL: andrzejmarek116@gmail.com
    volumes:
      - ./api/app:/srv/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./api/data:/var/lib/postgresql/data
networks:
  default:
    external:
      name: nginx-proxy
